import { describe, expect, it } from "vitest";
import { calculateInvestment } from "../lib/investmentEngine";
import type { InvestmentInput } from "../lib/investmentTypes";

/**
 * External Calculator.net results retrieved on 2026-09-28, NOT generated by this engine.
 * Full input URLs, displayed precision and evidence: docs/verification/calculator-net-golden.md.
 * These offline tests do not call the network or derive expected values from other solvers.
 */
const common = {
  startingAmount: 20000,
  contribution: 1000,
  returnRate: 0.06,
  years: 10,
  compoundFrequency: "annually",
  contributionFrequency: "monthly",
  contributionTiming: "end",
} as const;

const cases: {
  name: string;
  input: InvestmentInput;
  expected: number;
  tolerance: number;
}[] = [
  {
    name: "annual compounding, monthly end contribution (reference)",
    input: { ...common, mode: "endAmount" },
    expected: 198290.40,
    tolerance: 0.005,
  },
  {
    name: "monthly compounding, monthly end contribution",
    input: { ...common, mode: "endAmount", compoundFrequency: "monthly" },
    expected: 200267.28,
    tolerance: 0.005,
  },
  {
    name: "annual compounding, yearly end contribution",
    input: { ...common, mode: "endAmount", contributionFrequency: "yearly" },
    expected: 48997.75,
    tolerance: 0.005,
  },
  {
    name: "annual compounding, monthly beginning contribution",
    input: { ...common, mode: "endAmount", contributionTiming: "beginning" },
    expected: 199081.24,
    tolerance: 0.005,
  },
  {
    name: "investment length inverse for an external target of 200000",
    input: {
      mode: "years", startingAmount: 20000, contribution: 1000,
      endAmount: 200000, returnRate: 0.06, compoundFrequency: "annually",
      contributionFrequency: "monthly", contributionTiming: "end",
    },
    expected: 10.073,
    tolerance: 0.0005, // Calculator.net displays years to three decimal places.
  },
  {
    name: "return rate inverse for an external target of 200000",
    input: {
      mode: "returnRate", startingAmount: 20000, contribution: 1000,
      endAmount: 200000, years: 10, compoundFrequency: "annually",
      contributionFrequency: "monthly", contributionTiming: "end",
    },
    expected: 0.06145,
    tolerance: 0.000005, // Half of 0.001 percentage point, converted to decimal rate.
  },
];

describe("Calculator.net Golden Tests (external, recorded 2026-09-28)", () => {
  it.each(cases)("$name", ({ input, expected, tolerance }) => {
    const outcome = calculateInvestment(input);
    expect(outcome.ok).toBe(true);
    if (!outcome.ok) throw new Error(outcome.error.message);
    expect(Math.abs(outcome.result.solvedValue - expected)).toBeLessThan(tolerance);
  });
});
